version: '3.8'
services:
  mongo1:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
  mongo2:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
  mongo3:
    image: mongo
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"